PrintDesireApp/Controllers/PrintWebController.cs
using System.Web.Mvc;

namespace PrintDesireApp.Controllers
{
    [Authorize]
    public class PrintWebController : Controller
    {        
        public ActionResult Index()
        {
         //   throw new Exception();
           return View();
        }

        public ActionResult Product_Listing()
        {
            return View();
        }
        public ActionResult Product_Details()
        {
            return View();
        }
        public ActionResult Product_Catalogue()
        {
            return View();
        }
        public ActionResult Shoping_Cart()
        {
            return View();
        }
        public ActionResult Checkout()
        {
            return View();
        }
        public ActionResult Compaire()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult MobileCover_Listing()
        {
            return View();
        }
        public ActionResult MobileCover_Details()
        {
            return View();
        }

        public ActionResult Payment_Details()
        {
            return View();
        }
        public ActionResult Vendor_Payment()
        {
            return View();
        }
        public ActionResult Text_Editor()
        {
            return View();
        }

    }
}

PrintDesireApp/Views/PrintWeb/Compaire.cshtml

<div class="main-container">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-12">

            <!-- Best Seller -->
            <div class="col-lg-12 col-md-12 col-sm-12 hidden-xs">
                <div class="no-padding">
                    <span class="title">BEST SELLER</span>
                </div>
                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
                    <a style="overflow: hidden; position: relative;" href="http://demo.18maret.com/demo/mimity/v1.4/detail.html" class="link-p">
                        <img style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;" src="/images/product-8.jpg" alt="">
                    </a>
                    <div class="caption prod-caption">
                        <h4><a href="http://demo.18maret.com/demo/mimity/v1.4/detail.html">Penn State College T-Shirt</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
                        <p>
                        </p><div class="btn-group">
                            <a href="#" class="btn btn-default">$ 528.96</a>
                            <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                        </div>
                        <p></p>
                    </div>
                </div>
                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 visible-sm text-center">
                    <a style="overflow: hidden; position: relative;" href="http://demo.18maret.com/demo/mimity/v1.4/detail.html" class="link-p">
                        <img style="position: absolute; width: auto; height: auto; max-width: none; max-height: none; left: 50px; top: 0px;" src="/images/product-9.jpg" alt="">
                    </a>
                    <div class="caption prod-caption">
                        <h4><a href="http://demo.18maret.com/demo/mimity/v1.4/detail.html">Ohio State College T-Shirt</a></h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
                        <p>
                        </p><div class="btn-group">
                            <a href="#" class="btn btn-default">$ 924.25</a>
                            <a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
                        </div>
                        <p></p>
                    </div>
                </div>
            </div>
            <!-- End Best Seller -->

        </div>

        <div class="clearfix visible-sm"></div>

        <!-- Catalogue -->
        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="col-lg-12 col-sm-12 no-padding">
                <span class="title">PRODUCT COMPARISON</span>
            </div>
            <div class="clearfix"></div>
            <div class="table-responsive">
                <table class="table table-bordered comparison">
                    <thead>
                        <tr>
                            <td class="compare-product" colspan="5">Product Details</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="first_row">
                            <td>Product</td>
                            <td>Age Of Wisdom Tan Graphic Tee</td>
                            <td>Classic Laundry Green Graphic T-Shirt</td>
                            <td>Disc Jockey Print T-Shirt</td>
                        </tr>
                        <tr>
                            <td>Image</td>
                            <td>
                                <div class="thumbnail">
                                    <img src="/images/product-2-small.jpg" alt="product image">
                                </div>
                            </td>
                            <td>
                                <div class="thumbnail">
                                    <img src="/images/product-3-small.jpg" alt="product image">
                                </div>
                            </td>
                            <td>
                                <div class="thumbnail">
                                    <img src="/images/product-4-small.jpg" alt="product image">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>Price</td>
                            <td>$122.51</td>
                            <td>$628.96</td>
                            <td>$394.64</td>
                        </tr>
                        <tr>
                            <td>Model</td>
                            <td>Lorem</td>
                            <td>ipsum</td>
                            <td>dolor</td>
                        </tr>
                        <tr>
                            <td>Brand</td>
                            <td>consectetur</td>
                            <td>adipisicing</td>
                            <td>incididunt</td>
                        </tr>
                        <tr>
                            <td>Availability</td>
                            <td>In Stock</td>
                            <td>In Stock</td>
                            <td>In Stock</td>
                        </tr>
                        <tr>
                            <td>Rating</td>
                            <td>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o"></i>
                                </div>
                            </td>
                            <td>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </td>
                            <td>
                                <div class="product-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>Summary</td>
                            <td>Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</td>
                            <td>Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</td>
                            <td>Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><a class="btn btn-sm btn-warning" href="@Url.Action("Shoping_Cart", "PrintWeb")">Add To Cart</a></td>
                            <td><a class="btn btn-sm btn-warning" href="@Url.Action("Shoping_Cart", "PrintWeb")">Add To Cart</a></td>
                            <td><a class="btn btn-sm btn-warning" href="@Url.Action("Shoping_Cart", "PrintWeb")">Add To Cart</a></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><button class="btn btn-sm btn-danger"><i class="fa fa-remove"></i> Remove</button></td>
                            <td><button class="btn btn-sm btn-danger"><i class="fa fa-remove"></i> Remove</button></td>
                            <td><button class="btn btn-sm btn-danger"><i class="fa fa-remove"></i> Remove</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End Catalogue -->


    </div>
</div>

PrintDesireApp/Views/PrintWeb/Login.cshtml


<div class="main-container">
    <div class="center-block login-form">
        <div class="panel panel-default">
            <div class="panel-heading">Login Form</div>
            <div class="panel-body">
                <form role="form">
                    <div class="form-group">
                        <div class="input-group login-permission">
                             <label class="radio-inline"><input type="radio" name="optradio">Customer Login</label>
                              <label class="radio-inline"><input type="radio" name="optradio">Vendor Login</label>
                        </div>

                        <div class="input-group login-input">
                            <span class="input-group-addon"><i class="fa fa-user"></i></span>
                            <input class="form-control" placeholder="Username" type="text">
                        </div>
                        <br>
                        <div class="input-group login-input">
                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                            <input class="form-control" placeholder="Password" type="password">
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Remember me
                            </label>
                        </div>
                        <a type="submit" class="btn btn-sm btn-primary pull-right" href="@Url.Action("Index", "PrintWeb")"><i class="fa fa-long-arrow-right"></i> Login</a>
                        <button type="button" class="btn btn-xs btn-primary btn-login-social"><i class="fa fa-facebook"></i></button>
                        <button type="button" class="btn btn-xs btn-info btn-login-social"><i class="fa fa-twitter"></i></button>
                        <button type="button" class="btn btn-xs btn-danger btn-login-social"><i class="fa fa-google-plus"></i></button>
                        <hr>
                        <a href="@Url.Action("Register", "PrintWeb")" class="btn btn-success btn-sm pull-right">Register</a>
                        <a href="#" class="btn btn-warning btn-sm">Forgotten Password</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PrintDesireApp/Views/PrintWeb/MobileCover_Details.cshtml
<script src="~/Scripts/nicEdit-latest.js"></script>
<script type="text/javascript">
//<![CDATA[
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  //]]>
</script>
<div class="main-container">
    <div class="row">
        <div class="col-md-5">
            <div class="mobile_cover">
                <a href="#"> <img src="~/images/mobile/39_4_152.png" /></a>
            </div>
        </div>
        <div class="col-md-7">
            <div class="mobile_cover_details">
              <h4>Create Your Own iPhone 6 Mobile Cover</h4>
                <div class="form-group">
                   <label class="control-label col-md-2"> Quantity </label>
                    <div class="col-md-2">
                        <select class="form-control">
                            <option selected="selected">1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                    <div class="col-md-3 price_text">
                        <label class="control-label"><b> Rs.450.00 </b> </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 btn_block">
                        <a href="#" class="btn btn-default" data-toggle="modal" data-target="#myModalOne"> Preview</a>
                        <a href="@Url.Action("Shoping_Cart","PrintWeb")" class="btn btn-primary"> Add To Cart</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 personalize_design">
                       <h4> Personalize your design </h4>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <a href="#" class="btn btn-default" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-picture"></span> Add Images </a>
                        <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-text-width"></span> Add Text </a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12" id="sample">
                     <textarea name="area3" style="width: 100%; max-height: 55px; overflow:inherit;" class="form-control">
                         Enter Text  Here and customize text on your mobile cover
                    </textarea>
                     </div>
                </div>
            </div>
        </div>
            </div>
    <div class="row">
        <div class="col-md-12">
            <div class="product_description">
                <h4> PRODUCT DESCRIPTION:  </h4>
                <p> Create Your Own iPhone 6 Mobile Cover</p>
                <p>Adorn your phone cases with your very own photographs or designs. All you need to do is select a template , upload your photo/text and its done! Easy right ? Order now !</p>
            </div>
        </div>
        <div class="table_block">
            <table class="table table-bordered table-responsive">
                <thead>
                    <tr>
                        <th colspan="2" class="specifiaction"><h4>Specifications </h4></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Designed for</td>
                        <td>Apple iPhone 6</td>
                    </tr>
                    <tr>
                        <td>Finishing</td>
                        <td> 	Matte</td>
                    </tr>
                    <tr>
                        <td>Case Color</td>
                        <td>White</td>
                    </tr>
                    <tr>
                        <td>Waterproof</td>
                        <td>Yes</td>
                    </tr>
                    <tr>
                        <td>Material</td>
                        <td>White Velvet Finish Plastic</td>
                    </tr>
                    <tr>
                        <td>Printing Type</td>
                        <td>Digital Printing</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Trigger the modal with a button -->
@*<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>*@

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Select the image you want to upload</h4>
            </div>
            <div class="modal-body">
                <p>Upload Image</p>
                <div class="upload_img">
                    <input type="file" class="input_file" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<div id="myModalOne" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Mobile Cover</h4>
            </div>
            <div class="modal-body">
                <div class="image_preview">
                  <a href="#"> <img src="~/images/mobile/39_4_152.png" /></a>
               </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>



PrintDesireApp/Views/PrintWeb/Payment_Details.cshtml


<div class="main-container payment_details">
    <div class="row">
        <div class="col-md-3 col-sm-3"></div>
        <div class="col-md-6 col-sm-6 payment_block">
        <div class="form-group">
         <div class="col-md-12 pay_title">
             <h4>Payment Details</h4>
            </div>
         </div>
        <div class="form-group">
            <label class="control-label col-md-3"> Card Number </label>
            <div class="col-md-9">
                <input type="text" class="form-control" placeholder="xxxx-xxxx-xxxx-xxxx" required="required" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3"> Name On Card  </label>
            <div class="col-md-9">
                <input type="text" class="form-control" placeholder="Enter Name On Card" required="required"/>
            </div>
        </div>
          <div class="form-group">
            <label class="control-label col-md-3"> CVV Number  </label>
            <div class="col-md-9">
                <input type="text" class="form-control" placeholder="XXX" required="required"/>
            </div>
        </div>
           <div class="form-group">
            <label class="control-label col-md-3 col-sm-12 col-xs-12"> Expiry Date  </label>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <select class="form-control">
                    <option selected="selected">Month </option>
                    <option>01</option>
                    <option>02</option>
                    <option>03</option>
                    <option>04</option>
                    <option>05</option>
                    <option>06</option>
                    <option>07</option>
                    <option>08</option>
                    <option>09</option>
                    <option>10</option>
                    <option>11</option>
                    <option>12</option>
                </select>
            </div>
               <div class="col-md-4 col-sm-4 col-xs-6">
                <select class="form-control">
                    <option selected="selected">Year </option>
                    <option>16</option>
                    <option>17</option>
                    <option>18</option>
                    <option>19</option>
                    <option>20</option>
                    <option>21</option>
                    <option>22</option>
                    <option>23</option>
                    <option>24</option>
                    <option>25</option>
                    <option>26</option>
                    <option>27</option>
                    <option>28</option>
                </select>

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <p><strong>Note: </strong> In the next step you will be redirected to your bank's website to verify yourself. </p>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12" style="text-align:center;">
                <a href="#" class="btn btn-primary"> Pay Now</a>
            </div>
        </div>
     </div>
        <div class="col-md-3 col-sm-3"></div>
    </div>
</div>

PrintDesireApp/Views/PrintWeb/Register.cshtml

<div class="main-container">

    <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="white-container">
            <span class="title">REGISTER</span>
           <div class="col-md-12 registration">
               <label class="radio-inline"><input type="radio" name="optradio">Customer Registration</label>
               <label class="radio-inline"><input type="radio" name="optradio">Vendor Registration</label>
           </div>
            <!-- Form Register -->
            <form action="">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="first_name">First Name (*)</label>
                    <input class="form-control" id="first_name" type="text"><br clear="all">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="last_name">Last Name (*)</label>
                    <input class="form-control" id="last_name" type="text"><br clear="all">
                </div>
                  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="username">Mobile Number (*)</label>
                    <input class="form-control" id="Mobile" type="text"><br clear="all">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="username">Address (*)</label>
                    <input class="form-control" id="username" type="text"><br clear="all">
                </div>
                 <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" style="display:none;">
                    <label for="username">Contact Person (*)</label>
                    <input class="form-control" id="Contact" type="text"><br clear="all">
                </div>
                  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" style="display:none;">
                    <label for="username">Registration ID (*)</label>
                    <input class="form-control" id="Registration" type="text"><br clear="all">
                </div>
                 <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="email">Email (*)</label>
                    <input class="form-control" id="email" type="text"><br clear="all">
                </div>
                  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                      <label for="email">Gender (*)</label><br clear="all">
                     <label class="radio-inline"><input type="radio" name="optradio">Male</label>
                     <label class="radio-inline"><input type="radio" name="optradio">Female</label>
                </div><br clear="all">
                  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="username">Username (*)</label>
                    <input class="form-control" id="username" type="text"><br clear="all">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="password">Password (*)</label>
                    <input class="form-control" id="password" type="password"><br clear="all">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="confirm_password">Confirm Password (*)</label>
                    <input class="form-control" id="confirm_password" type="password"><br clear="all">
                </div>
                <div class="clearfix"></div>
                
                <div class="checkbox" style="padding-left:15px;">
                    <label>
                        <input type="checkbox"> I agree with <a href="#">Terms and Conditions.</a>
                    </label>
                    <span class="pull-right"><button class="btn btn-danger">Register</button> <button class="btn btn-default">Cancel</button></span>
                   
                </div>
             
            </form>
            <!-- End Form Register -->
        </div>

    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">

        <!-- Login Form -->
        <div class="white-container">
            <span class="title">ALREADY REGISTERED ?</span>
            <form role="form">
                <div class="form-group">
                    <div class="input-group login-input">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <input class="form-control" placeholder="Username" type="text">
                    </div>
                    <br>
                    <div class="input-group login-input">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <input class="form-control" placeholder="Password" type="password">
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> Remember me
                        </label>
                    </div>
                    <a type="submit" class="btn btn-sm btn-primary pull-right" href="@Url.Action("Index", "PrintWeb")"><i class="fa fa-long-arrow-right"></i> Login</a>
                    <button type="button" class="btn btn-xs btn-primary btn-login-social"><i class="fa fa-facebook"></i></button>
                    <button type="button" class="btn btn-xs btn-info btn-login-social"><i class="fa fa-twitter"></i></button>
                    <button type="button" class="btn btn-xs btn-danger btn-login-social"><i class="fa fa-google-plus"></i></button>
                </div>
            </form>
        </div>
        <!-- End Login Form -->

    </div>

</div>

PrintDesireApp/Views/PrintWeb/Text_Editor.cshtml
<div id="sample">
  
    <script src="~/Scripts/nicEdit-latest.js"></script>
     <script type="text/javascript">
//<![CDATA[
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  //]]>
  </script>
  <h4>
    First Textarea
  </h4>
  <textarea name="area1" cols="40">
</textarea><br />
  <h4>
    Second Textarea
  </h4>
  <textarea name="area2" style="width: 100%;">
       Some Initial Content was in this textarea
</textarea><br />
  <h4>
    Third Textarea
  </h4>
  <textarea name="area3" style="width: 300px; height: 100px;">
       HTML content default in textarea
</textarea>
</div>

PrintDesireApp/Views/PrintWeb/Vendor_Payment.cshtml
<div class="main-container">
    <div class="row">
        <div class="col-md-12">
            <h4 style="color:#0ff">Vendor Payment Details</h4>
        </div>
        </div>
      <table class="table table-bordered table-responsive">
          <thead>
              <tr>
                  <th colspan="2"> Payment to Vendor Cash/C.C	</th>
              </tr>
          </thead>
          <tbody>
              <tr>
                  <td>Customer ID</td>
                  <td>1002</td>
              </tr>
               <tr>
                  <td>Customer Name</td>
                  <td>John Smith</td>
              </tr>
              <tr>
                  <td>Amount </td>
                  <td>Rs 1500</td>
              </tr>
          </tbody>
      </table>  
   
</div>